handlers:
  - module: qlib.contrib.data.loader
    class: Alpha158DL
  - module: factors.custom_factors
    class: CustomFactor

corr_params:
  instruments: ["SH600519"]
  start_time: "2022-01-01"
  end_time: "2023-12-31"

corr_params_1min:
  instruments: ["SH600009"]
  start_time: "2020-09-14 09:30:00"
  end_time: "2021-06-11 14:59:00"


