handlers:
  - module: qlib.contrib.data.loader
    class: Alpha158DL
  - module: factors.custom_factors
    class: CustomFactor

corr_params:
  instruments: ["SH600519"]
  start_time: "2022-01-01"
  end_time: "2023-12-31"

# Embedding 配置
embedding_config:
  # Gemini 配置
  provider: "gemini"  # 可选: "gemini", "openai", "local"
  api_key: "${GEMINI_API_KEY}"  # 从环境变量读取API密钥
  proxy_url: http://127.0.0.1:1080
  model: "models/embedding-001"  # Gemini embedding模型
  request_delay: 3  # API请求间隔（秒），增加到3秒
  batch_size: 5  # 批处理大小，减少到5个
  max_retries: 3  # 最大重试次数
  timeout: 30  # 请求超时时间（秒）
